apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: clusters/ocp-prod/
    apps.open-cluster-management.io/reconcile-option: merge
  name: moc-metaconfig-ocp-prod
spec:
  channel: ocp-prod/moc-metaconfig
  placement:
    placementRef:
      kind: PlacementRule
      name: moc-metaconfig-ocp-prod-placement
